# Generated by Django 4.2.3 on 2023-10-13 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("indexer", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mergerequest",
            name="source_sha",
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name="mergerequest",
            name="target_branch",
            field=models.CharField(max_length=256, null=True),
        ),
    ]
