# Generated by Django 4.2.3 on 2023-07-11 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("indexer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="commit",
            name="created_ts",
            field=models.DateTimeField(null=True),
        ),
    ]
