# Generated by Django 4.2.3 on 2023-08-04 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("indexer", "0002_commit_created_ts"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="repository",
            options={"verbose_name_plural": "repositories"},
        ),
    ]
