# Generated by Django 4.2.3 on 2023-09-30 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("indexer", "0003_alter_repository_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="MergeRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("request_id", models.CharField(max_length=40)),
                ("title", models.CharField(max_length=1024)),
                ("state", models.CharField(max_length=32)),
                ("source_sha", models.CharField(default="", max_length=256)),
                ("source_branch", models.CharField(default="", max_length=256)),
                ("target_branch", models.CharField(default="", max_length=256, null=True)),
                ("merge_sha", models.CharField(default="", max_length=256, null=True)),
                ("created_at", models.CharField(max_length=32)),
                ("merged_at", models.CharField(max_length=32, null=True)),
                ("updated_at", models.CharField(max_length=32, null=True)),
                ("first_comment_at", models.CharField(max_length=32, null=True)),
                ("is_merged", models.BooleanField(default=False)),
                ("merged_by_username", models.CharField(max_length=32, null=True)),
                ("has_tests", models.BooleanField(default=False)),
                ("has_test_passed", models.BooleanField(default=False)),
                (
                    "repo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="merge_requests",
                        to="indexer.repository",
                    ),
                ),
            ],
            options={
                "db_table": "merge_requests",
            },
        ),
    ]
