# Generated by Django 4.2.3 on 2023-10-01 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("indexer", "0004_mergerequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="login_name",
            field=models.CharField(max_length=128, null=True),
        ),
    ]
